### ISSUE TITLE
No trailing zeros?

### ISSUE THREAD

**Issue by thielul** [KenKundert/quantiphy#1]
The output of 
```
Fhy = Quantity('1.0000 MHz')
print Fhy.render(prec=5)
```
is just 1 MHz. Shouldn't there be trailing zeros when I set the precision to 5, i.e., shouldn't it be 1.0000 MHz? How can I achieve this? (The trailing zeros indicate the resolution I'm working with so I don't want to throw them away).

**Comment by KenKundert** [comment]
That was not supported, but it seems like a good idea so I have added it. You can get the new feature by updating from github (the feature is not in pypi yet so 'pip install' will not do it). There is a new preference, strip_zeros. If you set it False, the trailing zeros will not be removed:
```
Quantity.set_prefs(strip_zeros=True)
Fhy = Quantity('1.0000 MHz')
print(Fhy.render(prec=5))
```
1 MHz
```
Quantity.set_prefs(strip_zeros=False)
Fhy = Quantity('1.0000 MHz')
print(Fhy.render(prec=5))
```
1.00000 MHz

**Comment by KenKundert** [comment]
Oh, and a precision of 5 results in 6 digits being displayed. This seemingly odd choice is modeled after the behavior of scientific calculators.

**Comment by thielul** [comment]
Awesome, cheers! Big up for your work!

**Comment by KenKundert** [comment]
Thanks!

**Comment by hmijail** [comment]
Found this issue while trying to make the `#` modifier work (I couldn't):
```
>>> r = Quantity(123000)
>>> f"{r:#.4}"
'123k'
>>> Quantity.set_prefs(strip_zeros=False)
>>> f"{r:#.4}"
'123.00k'
```
Is this a bug or am I misunderstanding something? 

This is in Quantiphy 2.19 on Python 3.12.2.

**Comment by KenKundert** [comment]
What were you expecting?

**Comment by hmijail** [comment]
Well, the docs say:

> The hash (#) is a literal hash that when present indicates that trailing zeros and radix should not be stripped from the fractional part of the number.

Sounds like the `#` is supposed to be equivalent to `(strip_zeros=False)`? And no other format modifier sounds close to that purpose.

Plus, `#` doesn't seem to do anything, which again sounds like maybe a bug?

```
>>> from quantiphy import Quantity
>>> r = Quantity(123000)
>>> f"{r:#.4}"
'123k'
>>> f"{r:.4}"
'123k'
>>> Quantity.set_prefs(strip_zeros=False)
>>> f"{r:#.4}"
'123.00k'
>>> f"{r:.4}"
'123.00k'
```

**Comment by KenKundert** [comment]
Okay, sorry about that.  I was looking at the wrong number.  I found and fixed the problem and have updated the github version.  Might take me a while to update the pypi version.
```
>>> from quantiphy import Quantity
>>> r = Quantity(123000)
>>> f"{r:#.4}"
'123.00k'
>>> f"{r:.4}"
'123k'
>>> Quantity.set_prefs(strip_zeros=False)
>>> f"{r:#.4}"
'123.00k'
>>> f"{r:.4}"
'123k'
```

**Comment by hmijail** [comment]
Maybe I'm being dense, but... shouldn't `f"{r:.4}"` reflect the preference, and therefore show the zeros in the last case?

**Comment by KenKundert** [comment]
No, I'm the one being dense. I have fixed this issue as well.
```
>>> from quantiphy import Quantity
>>> r = Quantity(123000)
>>> f"{r:#.4}"
'123.00k'
>>> f"{r:.4}"
'123k'
>>> Quantity.set_prefs(strip_zeros=False)
>>> f"{r:#.4}"
'123.00k'
>>> f"{r:.4}"
'123.00k'
```
Thanks!
