### ISSUE TITLE
Consider removing setup_requires from setup.py

### ISSUE THREAD

**Issue by johnthagen** [KenKundert/quantiphy#16]
Using `setup_requires` requires that `pip` has no way of controlling where these dependencies are located.

https://github.com/KenKundert/quantiphy/blob/4223ebb2fe3bf3047a9379307055672443280a05/setup.py#L30

See

- https://github.com/pytest-dev/pytest-xdist/issues/136
- https://pip.pypa.io/en/stable/reference/pip_install/#controlling-setup-requires

This makes it difficult/impossible to bundle this library for offline installs, for example, using [`pip download`](https://pip.pypa.io/en/stable/reference/pip_download/) or if a `pip.conf` file is needed to configure `pip` for a proxy settings, etc.

Typically test dependencies would be specified in `tox.ini`, which is already done:

https://github.com/KenKundert/quantiphy/blob/4223ebb2fe3bf3047a9379307055672443280a05/tox.ini#L15

This would make the sdist for this package much more portable. Users will likely just want to use `tox` to run the tests anyway?

**Comment by johnthagen** [comment]
Fixing #15 also helps with this, as users will normally have a wheel option and won't need to install the sdist itself.

**Comment by KenKundert** [comment]
Thanks!
I made the change on github. Do you need me to fix this in pypi right away, or can you wait for the next release?

**Comment by johnthagen** [comment]
Since the wheel has been uploaded now, this can wait until the next release.

Thanks for the great package!
