### ISSUE TITLE
Consider permissive license?

### ISSUE THREAD

**Issue by johnthagen** [KenKundert/quantiphy#18]
I noticed that the package is licensed as GPL:

https://github.com/KenKundert/quantiphy/blob/6d8bb4a33e7c58fd31387849ec09c6c7bf7fca03/setup.py#L37

This poses licensing challenges for integrating this package into projects that distribute their applications as binary installers using PyInstaller/PyOxidizer or for closed source/commercial use cases. Relicensing to a permissive license (such as MIT) would allow `quantiphy` to be used in a broader set of use cases.

This, of course, is completely your decision, and I will happily close this issue if you decline.

**Comment by KenKundert** [comment]
Okay, it is done. I have moved to the MIT license for the version currently in Github.  Expect to move it to PyPi in the next week or so.
