### ISSUE TITLE
prec='full' fails 

### ISSUE THREAD

**Issue by jumbofiatco** [KenKundert/quantiphy#20]
latest stable release
prec='full' fails for example 1.0 returns 1, 10.0 returns 10
probable bug at line 772
" if mantissa.find('.') >= 0:"

The check should exclude case prec='full'

**Comment by KenKundert** [comment]
QuantiPhy normally strips excess zeros from the right side of a number.  If you want to retain the zeros you should set *strip_zeros* to False.  For example:
```
    >>> for each in '1.0 1 10.0 100 100.000 100.001.split():                                                
    >>>     q = Quantity(each)                                                           
    >>>     print(each, q.render(prec='full'), q.render(prec='full', strip_zeros=False))
    1.0 1 1.0
    1 1 1
    10.0 10 10.0
    100 100 100
    100.000 100 100.000
    100.001 100.001 100.001 
```

**Comment by KenKundert** [comment]
Oh, and the latest stable version is 2.13, and it does not contain the line " if mantissa.find('.') >= 0:".  Perhaps you are not using the latest stable version.

**Comment by jumbofiatco** [comment]
Hi Ken, 

Thanks - works like a charm

On 2021-01-15 11:05 PM, Ken Kundert wrote:

> Oh, and the latest stable version is 2.13, and it does not contain the line " if mantissa.find('.') >= 0:". Perhaps you are not using the latest stable version. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/KenKundert/quantiphy/issues/20#issuecomment-761350739
[2]
