### ISSUE TITLE
translate to Russian Cyrillic

### ISSUE THREAD

**Issue by Irv1n** [KenKundert/quantiphy#22]
How I can translate SI units on Russian cyryllic?
like:
m: м (milli)
Ohm: Ом
k: к (killo)
Ghz: Гц
and so on

**Comment by KenKundert** [comment]
*QuantiPhy* treats units separately from scale factors.  With the units, you can  simply specify the units in Cyryllic:

```
    >>> print(Quantity(50, "Ом"))
    50 Ом
```

Or, you override existing units with:

```
    >>> print(Quantity('50 Ohms', units="Ом"))
    50 Ом
```

For scale factors, you would use the *map_sf* preference:

```
>>> Quantity.set_prefs(map_sf = dict(m = 'м', k = 'к', G = 'Гц'))

>>> print(Quantity(0.2, "Ом"))
200 мОм

>>> print(Quantity(4700, "Ом"))
4.7 кОм

>>> print(Quantity("2.4 GHz"))
2.4 ГцHz
```

Forgive me if I have messed up the conversions, I have no knowledge of Cyrillic.

**Comment by Irv1n** [comment]
map_sf works only in active python script or I can change scale factors for all files?

**Comment by KenKundert** [comment]
I'm sorry, but I don't understand your question.  *map_sf* only affects *QuantiPhy* when it renders numbers using SI scale factors.

**Comment by Irv1n** [comment]
> I'm sorry, but I don't understand your question. _map_sf_ only affects _QuantiPhy_ when it renders numbers using SI scale factors.

okey all work, but i have anothe question:
if i have value, for example (a = 0.025), i do: b = Quantity(a, "A"), and have result: 25 mA. How i can save value 25 and mA. Because if i use b.render(show_units=False) i have result 25m, or if i use b.units i have result: "A", but i need "mA"
Thank you.

**Comment by KenKundert** [comment]
QuantiPhy has no built-in support for this, but you can render the number to a string and simply split it.
```
>>> from quantiphy import Quantity                                               
                                                                                 
>>> current = Quantity(0.025, 'A')                                               
>>> print(current)                                                               
25 mA                                                                            
                                                                                 
>>> base, suffix = str(current).split(maxsplit=1)                                
>>> print(base)                                                                  
25                                                                               
>>> print(suffix)                                                                
mA
```
This assumes that the `spacer` preference is set to a space, which is the default.
