### ISSUE TITLE
setup.py no longer lists test requirements

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/quantiphy#23]
The latest release has removed the list of test requirements from setup.py. The tests now also require parametrize_from_file. Is there any reason why this was done? It makes it more tricky to package if you can't obviously see what other modules are required to run tests.

**Comment by KenKundert** [comment]
Testing is now performed via tox, which has its own dependency list.

**Comment by adhawkins** [comment]
Ah ok. Didn't realise. I'll be sure to monitor the tox config when packaging.
