### ISSUE TITLE
add type hints to allow static code analysis using mypy

### ISSUE THREAD

**Issue by PyroTom** [KenKundert/quantiphy#25]
Hey

i love your package as it eases lots of printing issues with engineering units ❤️

In my projects i use mypy for static code analysis. Actually quantiphy doesn't use type hints at all.
It would be great if we can add type hints and the `py.typed` to advertise that this package is using type hints.

http://www.mypy-lang.org/
https://peps.python.org/pep-0561/

Best regards
Tom

**Comment by KenKundert** [comment]
Well, I took another run at this and I think I have a reasonable set of type hints.  This is my first experience with them, so there may be issues I missed.  They are checked into this github repository if you would like to try them out.  I would appreciate any feedback you might have.

**Comment by KenKundert** [comment]
I have just released the latest version of QuantiPhy that includes type hint and pushed it to PyPi.
