### ISSUE TITLE
Added to conda-forge

### ISSUE THREAD

**Issue by SeanDS** [KenKundert/quantiphy#28]
My colleague needed this package for a project so added it to conda-forge: https://github.com/conda-forge/staged-recipes/pull/22266. If you want to become a maintainer of that repo then let me know.

**Comment by KenKundert** [comment]
Not at this time.  Thanks for the offer.

**Comment by KenKundert** [comment]
I think I am ready to take this on.  I have added a comment on the thread indicating that I am willing to be a maintainer.  Please add me to the list of maintainers.  And thanks!

**Comment by SeanDS** [comment]
You should have been added now, thanks.

**Comment by KenKundert** [comment]
Thanks Sean
