### ISSUE TITLE
Quantity returns the wrong value

### ISSUE THREAD

**Issue by AnSem-Ellwood** [KenKundert/quantiphy#3]
I noticed an error in the calculations when modifing my code to use Qunatity.  It decodes 315p correctly but the string '5p4' was translated into 5.  It is normal in electrical engineering to use the sci-unit instead of a decimal point and my own decode routine handled this ok.  values like 2k7 for resistors and 4p7 for capacitors is normal engineering notation.  It works fine if I change the string to 5.4p.

**Comment by KenKundert** [comment]
Quantiphy does not currently support that way of writing numbers. It expects the number first, then the prefix, then the units.

It is an interesting idea. You say that it is normal in electrical engineering to use the scale factor to replace the decimal point. Do you have any evidence of that? I tried a quick web search and found nothing.

I am an electrical engineer and have not seen this except in two unusual cases. First, after Y2K people started to designate years using this form, 2k1 for 2001, etc. That seems to have largely died off. Second, circuit designers sometimes want to put the intended signal level in a pin name. For example, I have seen avdd2p5V or ibias250nA. They use this form because a decimal point would not be legal in a pin name. However, in this case the 'p' in 2p5V means decimal point, not pico. So that brings up the question, how would you write 2.5V in your proposed format?

**Comment by AnSem-Ellwood** [comment]
Perhaps its a British thing?  When I became an Electronics engineer in 1982 it was standard practice.  Then all diagrams were drawn by hand (see http://mdfs.net/Info/Comp/BBC/Circuits/) and every letter was precious.  If you open up the circuit diagrams you will see a lot of values of 4k7 (E12 standard resistors) and 4n7 (same for capacitors).

**Comment by AnSem-Ellwood** [comment]
As a side note, I only noticed the problem because the output of my simulation changed when I changed from my own routine to Quantity.  This is because the initialization quietly failed and gave the wrong answer.  Perhaps it would be better to have failed noisily as this would have made debugging easier?

**Comment by AnSem-Ellwood** [comment]
I did not answer your question.  At AnSem where I work, we label 2.5V signals as 2v5.  This is different again  ;o) and just a short cut to save typing.  I personally don't like the use of p for decimal point.

**Comment by KenKundert** [comment]
Yeah, that is cool. How would you write something that does not use a scale factor, like 4.7Ώ?

The reason 5p4 was translated to 5 was that the units were taken to be 'p4'. If digits were disallowed from the units. So something like m2 to represent area in square meters would be out. I have to think about that one.

**Comment by KenKundert** [comment]
Whoops, we crossed paths. You answered my question while I was re-asking it.

Now that you mention it, I think I have seen 2v5. Does not seem very general. Would someone accept 4Ώ7, or 4ohms7.

I like the idea of supporting this way of writing number. It is compact and does not use special characters and so can be embedded in identifiers like pin names. I'll have to spend some time thinking about how to do it in a simple, general, and consistent manner.

**Comment by KenKundert** [comment]
Does this way of representing numbers have a name?

**Comment by AnSem-Ellwood** [comment]
4.7Ώ was normally written as 4R7 (go figure!).  Units were generally not included in values as the name appeared on a circuit diagram right next to something that was instantly recognisable as a resistor or capacitor.  Also 4k7 was unlikely to be a capacitor since it would have been the size of a house ;o).  I see your problem with respect to interpretation, though I did specify the unit separately as a second argument.

I never knew a name for this standard but a quick google search found this:

https://embeddedpro.wordpress.com/tag/cermet/

Its seems it is indeed a British standard BS1852.

**Comment by KenKundert** [comment]
Apparently it is now an international standard: IEC 60062, informally called [RKM code](https://en.wikipedia.org/wiki/RKM_code).
I've been an electrical engineer for a long time and never knew. And memories of old schematics that contained these codes are coming back to me as well.
Things are starting to come together for me, but I need to try some things. I'm thinking that I can add a preference that turns on RKM mode, meaning that Quantity('5p4') will first try interpreting a string a RKM code, and if there is no match it will revert back to its normal behavior. For output, I would add a special mode for that too. I'll get back to you on this.

By the way, in my day job I do analog verification. Does AnSem need any help in that area?

**Comment by KenKundert** [comment]
I have created a separate package that converts between RCM codes and QuantiPhy quantities. Give it a try and let me know what you think. It is on [github](https://github.com/KenKundert/rkm_codes). Documentation is in the form of a README. You can install it with pip.
    `pip3 install --user rkm_codes`
It only supports python3, hopefully that is what you are using. You can use it as follows:
`>>> from rkm_codes import from_rkm, to_rkm`
`>>> r = from_rkm('6K8')`
`>>> r`
`Quantity('6.8k')`
`>>> to_rkm(r)`
`'6K8'`
