### ISSUE TITLE
meter is not recognized

### ISSUE THREAD

**Issue by Elia1996** [KenKundert/quantiphy#30]
Hi,
first of all great package! 
I've some problem to convert meter, for example:
`Quantity('10 m').units`
return  an empty string. I've also a strange behavior with:
`Quantity('10 meter').units`
Which return 'eter'.

I think it is a problem in the parsing, i thought that it is more intuitive that '10 m' is recognized like 10 meter instead of  0.01 without unit.
Package version 2.19
Thanks in advance.

**Comment by KenKundert** [comment]
QuantiPhy uses a different approach compared to other units packages.  Most other package have a database of known units and so would recognize 'meter' as a unit.  Instead QuantiPhy recognizes scale factors and treats whatever is left after the scale factor is removed as the unit.  Both the units and the scale factor are optional.  If a suffix can be either a scale factor or a unit, it is treated as a scale factor by default.  Thus, '10 m' becomes 10 milli and '10 meter' becomes 10 milli-eter.

This approach is nice in that it does not require QuantiPhy to be limited to a set of known units, but it is innately ambiguious, as you have discovered.  There are a number of ways of configuring QuantiPhy to overcome this.  I recommend you read [Ambiguity of Scale Factors and Units](https://quantiphy.readthedocs.io/en/stable/user.html#ambiguity-of-scale-factors-and-units).

**Comment by Elia1996** [comment]
Thanks for your answer! 
So at the end It can be solved with:
`Quantity.set_prefs(known_units="m meter") `
