### ISSUE TITLE
DeprecationWarning when running py.test

### ISSUE THREAD

**Issue by Djailla** [KenKundert/quantiphy#4]
Hello,

When running tests using quantiphy, I got this warning :

`python3.6/site-packages/quantiphy.py:1268: DeprecationWarning: Flags not at the start of the expression '\\A\\s*(?P<sign>[-+]?)' (truncated)
15:21:54     for pattern, get_mant, get_sf, get_units in [`

Anyone aware of this ?

Regards

**Comment by Djailla** [comment]
Up ?

**Comment by KenKundert** [comment]
Oops, sorry. I did not see this until just today.

I also saw those warnings back in November and fixed them in version 2.4.2.  If you get the latest version from Github you should no longer see the warning.  I will update pypi soon.
