### ISSUE TITLE
Adding new unicode character for micro: "µ" as an alternative to μ

### ISSUE THREAD

**Issue by TKaluza** [KenKundert/quantiphy#5]
Trying to convert my string "4.6 µH" it raised a ValueError. 
As it seems in UTF there's a extra character for micro (compare https://unicodelookup.com/): 

  -    **micro sign**    --> µ | 0xB5
   -    **greek small letter mu**  --> μ | 0x3BC

I do not see a reason for not supporting this. 😸 

Maybe a extra option could be added for displaying the mu.

**Comment by KenKundert** [comment]
Good catch. I have added support for both.
By default I accept either on input and micro on output.

I don't see the need for an additional option that controls which to use on output. One could use map_sf to override the use of micro to get mu if desired.

This is fixed in version 2.4.5.

**Comment by TKaluza** [comment]
I totally agree. Micro is the right ouput 😄 

Some fonts use the same symbol for the greek smal letter or they use different ones. Then the "right" one should be used. 

Thank you!
