### ISSUE TITLE
Unitless scales

### ISSUE THREAD

**Issue by SeanDS** [KenKundert/quantiphy#6]
Hi Ken,

This is a great library. One feature I think I am missing though is some way to parse strings like "120 dB" as absolute values without requiring units. As far as I understand, I have to define a conversion like:

```python
UnitConversion('V', 'dBV', from_dB, to_dB)
```

but what if my unit is dimensionless (such as an op-amp's open loop gain, commonly expressed in datasheets in `dB`)? I tried

```python
UnitConversion('', 'dB', from_dB, to_dB)
```

but this doesn't seem to work. Is this behaviour somehow supported?

**Comment by KenKundert** [comment]
Thank you.

The way I would handle this situation would be to first apply units to the value, then do the conversion. So, something like:
```python
UnitConversion('V/V', 'dB', from_dB, to_dB)                                      
gain = Quantity(10, 'V/V')
print(gain.scale('dB'))
```
or
```python
UnitConversion(('V/V', 'A/A'), 'dB', from_dB, to_dB)

Vgain = Quantity(10, 'V/V', scale='dB')
Igain = Quantity('1M', 'A/A', scale='dB')                                            
print(Vgain, Igain)
```

**Comment by KenKundert** [comment]
Alternatively, you can avoid using `UnitConversion` like:
```python
def to_dB(value, units=''):
    return 20*math.log10(value), 'dB'

gain = Quantity(10, scale=to_dB)
print(gain.scale('dB'))
```

(In answering this question I discovered that the scaling functions used by Quantity are different than those used by UnitConversion. That was a surprise and does not seem ideal, but I have not decided how to make them consistent. Thus, the to_dB function used in this answer is different from the one used in the previous answer.)

**Comment by SeanDS** [comment]
Your first approach of applying units to the quantity seems like the best approach for my use-case. Thanks!

BTW, does `quantiphy` detect scales from parsed strings? Ideally I'd like to be able to be able to parse strings with or without `dB` without first looking at the string to see if it has a scale, i.e. the following condition should be true:
```python
Quantity("120 dB") == Quantity("1e6")
```
Is this possible or planned?

**Comment by KenKundert** [comment]
QuantiPhy will not scale unless you tell it to, but I think you can get what you want with something like this:
```python
UnitConversion('V/V', 'dB', from_dB, to_dB)

for gain in '100 100V/V 40dB'.split():
    lgain = Quantity(gain, 'V/V', scale='V/V')
    print(lgain, lgain.render(scale='dB'))
```
In this example `gain` is a string that may or may not have units.  If it does not have units, `Quantity` will use the second argument as the default units. Finally the third argument says to convert the given value to 'V/V'. The first two values will not be affected because they already are 'V/V', but the third value is 'dB', so `Quantity` will use `from_dB` to convert it to 'V/V'.
